//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteManagerEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public int u_id { get; set; }
        public string u_email { get; set; }
        public string u_pwd { get; set; }
        public string u_nom { get; set; }
        public string u_prenom { get; set; }
    
        public virtual ICollection<Note> Notes { get; set; }
    }
}
